// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXgUT9OaFKCBycua2S4tqq0OoCMNePtjA',
    appId: '1:767590465486:web:a82a3ef2c06ffa89e1b59f',
    messagingSenderId: '767590465486',
    projectId: 'testflutter-7b2a3',
    authDomain: 'testflutter-7b2a3.firebaseapp.com',
    storageBucket: 'testflutter-7b2a3.appspot.com',
    measurementId: 'G-SX7SX5049Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq-O0zxLphUXQju_r9n6SzmkxSYoJhIH8',
    appId: '1:767590465486:android:b743b3c7d6e4ecbbe1b59f',
    messagingSenderId: '767590465486',
    projectId: 'testflutter-7b2a3',
    storageBucket: 'testflutter-7b2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCINTJEwT6OmgFPY3EC9oElN13191nZvuU',
    appId: '1:767590465486:ios:ed5cfbcf7dc6ae78e1b59f',
    messagingSenderId: '767590465486',
    projectId: 'testflutter-7b2a3',
    storageBucket: 'testflutter-7b2a3.appspot.com',
    iosClientId: '767590465486-1vsmnccm477q9skmiu906qs58i0pvbva.apps.googleusercontent.com',
    iosBundleId: 'com.example.plz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCINTJEwT6OmgFPY3EC9oElN13191nZvuU',
    appId: '1:767590465486:ios:ed5cfbcf7dc6ae78e1b59f',
    messagingSenderId: '767590465486',
    projectId: 'testflutter-7b2a3',
    storageBucket: 'testflutter-7b2a3.appspot.com',
    iosClientId: '767590465486-1vsmnccm477q9skmiu906qs58i0pvbva.apps.googleusercontent.com',
    iosBundleId: 'com.example.plz',
  );
}
